- bwapi/BWAPI/Source/BWAPI/GameUnits.cpp
So as I noticed at least in most of the cases for units after morphing `isCompleted` becomes false after they morphed and stays so until they fully built / spawned, this includes refineries and zerg units. Actually, while for zerg units there is another `UnitMorph` event sent after their spawned from egg / cocoon, for refinery it seems like there's no way to understand when it becomes completed.
Anyway it seems like it's right behavior to send `UnitCompleted` each time `IsCompleted` is changed from `false` to `true`, so I believe `wasCompleted` needs to be reset just after the unit was morphed.
> Fix UnitCompleted event not being sent for units after morphing.

- Release_Binary/Starcraft/bwapi-data/bwapi.ini
- bwapi/BWAPI/Source/BWAPI/AutoMenuManager.cpp
- bwapi/BWAPI/Source/BWAPI/AutoMenuManager.h
e.g. for selecting 2 vs 2 for game_type TOP_VS_BOTTOM or 7500 for GREED
it works by using setSelectedByString() and seems to work for all game types
> auto_menu: added game_type_extra option to bwapi.ini

- Release_Binary/Starcraft/bwapi-data/bwapi.ini
- bwapi/BWAPI/BWAPI.vcxproj
- bwapi/BWAPI/BWAPI.vcxproj.filters
- bwapi/BWAPI/Source/BWAPI/Streams.cpp
- bwapi/BWAPI/Source/DLLMain.cpp
- bwapi/BWAPI/packages.config
- bwapi/BWAPILIB/BWAPILIB.vcxproj
- bwapi/BWAPILIB/BWAPILIB.vcxproj.filters
- bwapi/BWAPILIB/packages.config
- bwapi/include/BWAPI.h
- bwapi/include/BWAPI/BroodwarOutputDevice.h
- bwapi/include/BWAPI/Color.h
- bwapi/include/BWAPI/Streams.h
Addresses #627 by adding two functions, `openConsole()` and `autoOpenConsole()`, the first opens a console immediately, while the second will make it open when/if something is written to `std::cout/cerr`. Via bwapi.ini they which can also be configured to be called when bwapi is first attached.
It also adds 4 output streams: `BWAPI::bwout/bwerr` and `BWAPI::out/err`.
`bwout/bwerr` prints inside Starcraft via `Game::printf()` but bwerr is colored red.
`out/err` writes to both `bwout/bwerr` and `std::cout/cerr`.
Things I'm unsure about:
- The names for the streams, `BWAPI::bwout/bwerr` and `BWAPI::out/err`.
- This adds a dependency on boost, but only when compiling bwapi itself.
- In which folder/filter to include the files in visual studio.
- The version number in the @since tags (I used …
> console opening and output streams

- bwapi/DocumentationGen/playertypes.cpp
- bwapi/DocumentationGen/techtypes.cpp
- bwapi/DocumentationGen/unittypestestgen.cpp
- bwapi/include/BWAPI/SetContainer.h
Summary:
We should include and only include headers that used in the .cpp file.
This commit fixes a few of such files.
Also it removes some redudant copy and move constructors of SetContainer
as they are implicitly defined thus unnecessary. This change compiles under VS2015.
> Some fixes to header include.

- bwapi/BWAPI/Source/BW/Bitmap.cpp
- bwapi/BWAPI/Source/BWAPI/GameDrawing.cpp
- bwapi/BWAPI/Source/BWAPI/GameImpl.cpp
- bwapi/BWAPI/Source/BWAPI/GameMenu.cpp
- bwapi/BWAPI/Source/BWAPI/Map.cpp
- bwapi/BWAPI/Source/DLLMain.cpp
- bwapi/Util/Source/Util/Clamp.h
- bwapi/Util/Source/Util/Sha1.cpp
- bwapi/Util/Source/Util/Sha1.h
- bwapi/Util/Util.vcxproj
- bwapi/Util/Util.vcxproj.filters
All other file names follow the CamelCase convention. This commits fixes
these three files.
> Rename clamp.h to Clamp.h and sha1.{h,cpp} to Sha1.{h,cpp}.

- Release_Binary/Starcraft/bwapi-data/bwapi.ini
- bwapi/BWAPI/Source/BWAPI/AutoMenuManager.cpp
- bwapi/BWAPI/Source/BWAPI/AutoMenuManager.h
- bwapi/BWAPI/Source/Config.h
- bwapi/BWAPI/Source/GameUpdate.cpp
- bwapi/SNP_DirectIP/SNP/LocalPC.cpp
- bwapi/SNP_DirectIP/SNP/SNPModule.cpp
- bwapi/Util/Source/Util/SharedMemory.cpp
- bwapi/Util/Source/Util/SharedMemory.h
This addresses #614 some smaller stuff. 
I'd very much like to have everything looked at. Some questions are:
Replacing `Global\\` with `Local\\` in LocalPC.cpp seems to fix #614 for me, but does it work on other windows versions?
Should both the shared memory and the mutex be local? I seems to work when the mutex is either.
Btw, we use the `Local\\` prefix for two other shared memories:
- "Local\\bwapi_shared_memory_" << processID
- "Local\\bwapi_shared_memory_game_list"
> Local PC for win10 and more

- bwapi/BWAPI/Source/WMode.cpp
Calling wOriginalProc directly is not guaranteed to work as excepted.
https://msdn.microsoft.com/en-us/library/windows/desktop/ms633584(v=vs.85).aspx says "You must use the CallWindowProc function to call the window procedure."
At least on my system, this is necessary when using BWAPI with an OpenGL-based windowed mode hack, as the system's OpenGL driver injects its own *unicode* WndProc hook.
> Use CallWndProc to call the original WndProc

- bwapi/BWAPIClient/Source/Convenience.h
- bwapi/Util/Source/Util/Convenience.h
StrCopy is currently copying the size of dst without checking if src is long enough for it. This includes a bound check.
> Fix overflow in StrCopy

- bwapi/AIModuleLoader/AIModuleLoader.vcxproj
- bwapi/BWAPI/BWAPI.vcxproj
- bwapi/BWAPI/Source/BWAPI/BulletImpl.h
- bwapi/BWAPI/Source/BWAPI/GameImpl.cpp
- bwapi/BWAPI/Source/BWAPI/PlayerImpl.h
- bwapi/BWAPI/Source/BWAPI/RegionImpl.h
- bwapi/BWAPI/Source/BWAPI/Server.cpp
- bwapi/BWAPI/Source/GameUpdate.cpp
- bwapi/BWAPIClient/BWAPIClient.vcxproj
- bwapi/BWAPILIB/BWAPILIB.vcxproj
- bwapi/BWAPILIB/Source/BWAPI.cpp
- bwapi/BWAPILIBTest/BWAPILIBTest.vcxproj
- bwapi/BWAPI_PluginInjector/BWAPI_PluginInjector.vcxproj
- bwapi/BWScriptEmulator/BWScriptEmulator.vcxproj
- bwapi/DevAIModule/DevAIModule.vcxproj
- bwapi/DocumentationGen/DocumentationGen.vcxproj
- bwapi/ExampleAIClient/ExampleAIClient.vcxproj
- bwapi/ExampleAIModule/ExampleAIModule.vcxproj
- bwapi/ExampleTournamentModule/ExampleTournamentModule.vcxproj
- bwapi/SNP_DirectIP/SNP_DirectIP.vcxproj
- bwapi/SVNRevGen/SVNRevGen.vcxproj
- bwapi/Storm/Storm.vcxproj
- bwapi/TestAIModule/TestAIModule.vcxproj
- bwapi/Util/Util.vcxproj
- bwapi/include/BWAPI.h
- bwapi/include/BWAPI/Position.h
- bwapi/include/BWAPI/Region.h
- bwapi/include/BWAPI/SetContainer.h
Version of 4.1.2 which compiles with vc140(Visual Studio 2015). Example client bot works.
Picked the relevant commits from master, and made some changes to aid in building client+libs: pinned the revision number to 4708, don't run the script to copy over dlls in starcraft/bwapi-data.
> 4.1.2 vc140 compat

- CMake/BWAPI/CMakeLists.txt
- CMake/Client/CMakeLists.txt
- CMake/README.md
- bwapi/BWAPI/Source/BW/Bitmap.cpp
- bwapi/BWAPI/Source/BW/CheatType.cpp
- bwapi/BWAPI/Source/BWAPI/AutoMenuManager.cpp
- bwapi/BWAPI/Source/BWAPI/GameDrawing.cpp
- bwapi/BWAPI/Source/BWAPI/GameEvents.cpp
- bwapi/BWAPI/Source/BWAPI/GameImpl.cpp
- bwapi/BWAPI/Source/BWAPI/GameMenu.cpp
- bwapi/BWAPI/Source/BWAPI/Map.cpp
- bwapi/BWAPI/Source/Config.cpp
- bwapi/BWAPI/Source/Config.h
- bwapi/BWAPI/Source/DLLMain.cpp
- bwapi/BWAPI/Source/Detours.cpp
- bwapi/BWAPI/Source/GameUpdate.cpp
- bwapi/BWAPILIB/Source/BroodwarOutputDevice.cpp
- bwapi/BWAPILIB/Source/Streams.cpp
- bwapi/Util/Source/Util/Clamp.h
- bwapi/Util/Source/Util/Path.h
- bwapi/Util/Source/Util/StringUtil.h
- bwapi/include/BWAPI/BroodwarOutputDevice.h
- bwapi/include/BWAPI/Unitset.h
* Adds CMake scripts to use BWAPI and BWClient as static libraries. It is potentially able to build BWAPI DLL too, but something is not right with compile flags, starting with this DLL freezes, so i commented it out.
* Boost dependency is removed from the code (not from the VS solution)
See CMake/README.md
Creates bwapi/Release/BWAPI-Static.lib and bwapi/Debug/BWAPI-Staticd.lib
Creates bwapi/Release/BWAPIClient.lib and bwapi/Debug/BWAPIClientd.lib
Compile tested with VS2017 and VS2015.
EXE Client bot works both debug (VS Debug build) and release (VS Release build)
* Broodwar output streams are commented out. Something must be done.
* NuGet packages must be removed for BWAPI, BWAPILib and BWAPIClient
* New include files should be added to VS solution, they are located in `bwapi/Utils` …
> CMakeLists to build client mode libraries + fix for VS2017

- bwapi/BWAPI/Source/BWAPI/GameEvents.cpp
- bwapi/BWAPI/Source/BWAPI/GameInternals.cpp
This fixes a Broodwar crash when starting subsequent multiplayer games with speed_override = 0. It does this by making sure that BW's speed arrays are reset to the stock values when games finish, and setting the speed override only on game start. Applies to BWAPI 4.1.2 onwards at least.
Replicating the crash: Set speed_override = 0 in BWAPI.ini. Start a UDP or Local PC multiplayer game. Surrender. Start another game. BW should immediately crash. Doesn't matter whether you have a bot attached or computer opponents. Other network modes may also crash but are untested.
> Fix crash when starting second multiplayer game with speed_override=0

- bwapi/include/BWAPI/UnitType.h
- bwapi/include/BWAPI/WeaponType.h
Eliminating more @todos in the docs.
Splash damage source:  http://liquipedia.net/starcraft/Damage#Splash_Damage
Halt distance source: @tscmoo
> Document weapon splash and halt distance

- bwapi/include/BWAPI/Position.h
`std::tie` is considered impractical, slow and dangerous. While it does the job here, `std::tie` should not be used for lexicographic ordering for performance reasons in less optimized environments, like when running your bot in debug mode.
To illustrate this, I put together a small [benchmark](http://quick-bench.com/jdHro_IfUNKELMR3z9Yk2EzGVsc). The performance in Release (-O3) [is unaffected](http://quick-bench.com/-nieXCPkCW8StNYhyEX4n18_qc8).
> Avoid std::tie in BWAPI::Point

- bwapi/BWAPI/BWAPI.vcxproj
- bwapi/BWAPI/Source/BWAPI/Command.h
- bwapi/BWAPI/Source/BWAPI/CommandTemp.h
- bwapi/BWAPI/Source/BWAPI/GameCommands.cpp
- bwapi/BWAPI/Source/BWAPI/GameImpl.h
- bwapi/BWAPI/Source/BWAPI/GameInternals.cpp
- bwapi/BWAPI/Source/BWAPI/UnitImpl.cpp
- bwapi/BWAPIClient/BWAPIClient.vcxproj
- bwapi/BWAPIClient/Source/UnitImpl.cpp
Latcom has always been somewhat messy with BWAPI. We've seen issues related to negative minerals, crazy wrong supply etc. My goal with this rewrite was of course not to make latcom perfect (way too hard of a problem) but I wanted to make sure none of these bugs were expected. Old latcom code was also a lot harder to maintain and just wasn't built around that there could be a turn size that isn't 1.
New latcom code handles any turn size or latency. It is based on the [timings collected by jaj22](https://docs.google.com/document/d/1a-6NqHI3Leqe6FOZph_K5NLWx27VG1sa87bRSdjQotU/edit).
If there are any questions or requests, I should be able to look at them shortly.
Fixes, #781, #652, #613, etc. I haven't gone back further but there are probably more issues related to latcom.
> Full latcom rewrite

- .gitignore
- bwapi/BWAPI/BWAPI.vcxproj
- bwapi/BWAPIClient/BWAPIClient.vcxproj
- bwapi/BWAPILIB/BWAPILIB.vcxproj
- bwapi/BWAPI_PluginInjector/BWAPI_PluginInjector.vcxproj
- bwapi/SNP_DirectIP/SNP_DirectIP.vcxproj
- bwapi/SVNRevGen/SVNRevGen.vcxproj
- bwapi/bwapi.sln
This should let people integrate BWAPI builds into their own. This can for example be used for having BWAPI projects available in unit/integration tests for bots or BWAPI dependent libraries as a submodule.
Example: https://ci.appveyor.com/project/N00byEdge/bwem-community/build/1.0.17-master/job/5ymygb5t199tjva6
I also had to patch SVNRevGen so that it generated `svnrev.h` in the correct BWAPI directory, and not relative to the solution (since BWAPI isn't the active solution). It will now generate relative to the project itself.
> Make BWAPI integrable into other projects

- bwapi/BWAPI/Source/BWAPI/Server.cpp
I also audited the other fields of PlayerData; all are copied to the client either at the start of the game or on each frame.
(This PR looks better than my last attempt. :-))
> #790 Tell Clients about player->isParticipating

- bwapi/include/BWAPI/Player.h
https://github.com/bwapi/bwapi/pull/787 but on the develop branch
> Specified that Player.weaponDamageCooldown only applies to ground attacks

- bwapi/Backend/libprotobuf-lite/libprotobuf-lite.vcxproj
- bwapi/Backend/libprotobuf-lite/libprotobuf-lite.vcxproj.filters
Fixes the absolute paths to @heinermann 's download folder and uses the relative path. Also removed the unused imports from projects not included.
> Fix libprotobuf-lite build

- bwapi/Shared/Templates.h
isVisible() is not synced to a client when a unit is removed, but it is marked as nonexistent.
Clients should always check exists() on units, not doing so makes this mineral check algorithm see a ghost mineral field. This does not occur on modules since there isVisible() is properly updated.
> Fix client desync when trying to expand to base with blocking minerals

- bwapi/BWAPI/Source/BWAPI/UnitImpl.cpp
- bwapi/BWAPI/Source/BWAPI/UnitUpdate.cpp
- bwapi/Shared/UnitShared.cpp
This should fix issue #847 
Fresh 4.4 without the fix:
Fixed 4.4:
Getting resource amount from own refinery works fine too:
Code used to test:
```cpp
void ExampleAIModule::onFrame()
{
for (auto& u : Broodwar->getAllUnits())
{
if (u->getType().isRefinery()) {
std::string s = std::to_string(u->getInitialResources());
std::string s2 = std::to_string(u->getResources());
Broodwar->drawTextMap(u->getInitialPosition(), s.c_str(), Colors::White);
Broodwar->drawTextMap(u->getInitialPosition() + Position(0, 16), s2.c_str(), Colors::White);
}
}
}
```
> Fixes #847

- 1.16.1/SNP_DirectIP/src/DirectIP/DirectIP.cpp
- 1.16.1/SNP_DirectIP/src/DirectIP/Settings.cpp
- 1.16.1/SNP_DirectIP/src/DirectIP/Settings.h
- 1.16.1/SNP_DirectIP/src/DirectIP/SettingsDialog.cpp
- 1.16.1/SNP_DirectIP/src/DirectIP/SettingsDialog.h
- 1.16.1/SNP_DirectIP/src/DirectIP/SettingsEnvironment.cpp
- 1.16.1/SNP_DirectIP/src/DirectIP/SettingsEnvironment.h
- 1.16.1/SNP_DirectIP/src/DirectIP/SettingsFile.cpp
- 1.16.1/SNP_DirectIP/src/DirectIP/SettingsFile.h
Ported https://github.com/bwapi/bwapi/pull/883 to the `develop` branch. This allows configuring the DirectIP SNP with either a config file or environment variables which makes automation easier. For example, I use this https://zeta-two.com/challenges to automate bots joining games.
> Add more ways to provide settings to DirectIP SNP

- 1.16.1/SNP_DirectIP/src/LocalPC/LocalPC.cpp
Copied from original PR #886 :
During my tests I found that even 5-6 bots seem to saturate the small buffer. That leads to spurious crashes or inability to join games in the first place.
I did try with 32, which still was not enough - so I upped it to ~1Meg, maybe it's a bit much but even 8 bots did not trigger any warning in a full game.
> Increase packet buffer, to prevent saturation
